### ISSUE TITLE
'master' branch should always point to SNAPSHOT

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/ejb-api#101]
After reviewing the [jenkins log files](https://ci.eclipse.org/ejb/job/ejb-api-release/32/consoleFull) and the [infra release job](https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job), I have come to the conclusion that all pom.xml should point to SNAPSHOT in the master branch to perform a successful release.

To fix this issue:
- Revert ea0a7bd4680d3ef1e2e0fd37332e66ebad46c11e
- Remove the following lines in the Jenkins job configuration under the build->execute shell => Line 15
```
sed -i s/4.0.0-RC1/4.0.0-SNAPSHOT/g pom.xml api/pom.xml spec/pom.xml
sed -i s,https://oss.sonatype.org/,https://jakarta.oss.sonatype.org/, pom.xml api/pom.xml spec/pom.xml
```
The first line replaces the RELEASE_VERSION with SNAPSHOT_VERSION in all pom files. This is unnecessary if all poms are already pointing to SNAPSHOT.

The second line is not required since this configuration is part of parent pom and this was removed as part of commit https://github.com/eclipse-ee4j/ejb-api/commit/7151df1e995a97cf11b2d4683f1796c8a6913b6d#diff-8658bb96fff6ac848cd28d3242fce067L375

**Comment by hussainnm** [comment]
Closing this issue as RC2 staged successfully. The second point mentioned in the issue will have no effect during build. It is better if it is removed to avoid any confusion in the future about the two lines.

**Comment by tkburroughs** [comment]
@hussainnm Per the second point above, I did remove the 2 lines in the Jenkins job configuration.
