### ISSUE TITLE
4.0.0 Release finalization steps

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/ejb-api#133]
Now that the specification committee ballot has concluded, the following steps need to be completed by the spec team:

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [ ] merge any final release branch as appropriate for the branch management for the project.
N/A

**Comment by jansupol** [comment]
We have Jersey 3.0.0 and Tyrus 2.0.0 depending on the EJB API. Do you have any plan on pushing the API to central, so can we push Jersey and Tyrus?

**Comment by jansupol** [comment]
To push a bit further, there is EclipseLink and Eclipse Metro that depend on the EJB API, too.

**Comment by senivam** [comment]
Hello @jeanouii , just a quick question, if there is anything which prevents EJB API from being promoted to maven central? Thank you.

**Comment by senivam** [comment]
@jeanouii and could you please take a look at #135 before sending EJB API to central?

**Comment by arjantijms** [comment]
GlassFish 6.0.0, which should be released before the Jakarta lifestream (at 8 December 2020) depends on this as well, in addition to it depending on Jersey, Tyrus, EclipseLink and Metro.

**Comment by senivam** [comment]
> GlassFish 6.0.0, ... depending on Jersey, Tyrus, EclipseLink and Metro.

and all of those depends in turn on EJB :)

**Comment by jeanouii** [comment]
I just did the promote 

`[INFO] RC-Releasing staging repository with IDs=[jakartaejb-1003]

Waiting for operation to complete...
..

[INFO] Released`

**Comment by arjantijms** [comment]
EJB is now in central :) 

https://repo1.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/4.0.0/

**Comment by jeanouii** [comment]
Closing as everything has been completed now.

**Comment by senivam** [comment]
thanks for releasing EJB :)
