### ISSUE TITLE
4.0.0 EJB Staging duplicate

### ISSUE THREAD

**Issue by senivam** [eclipse-ee4j/ejb-api#135]
There is an issue in EJB staging which shall be solved before promoting of EJB API to central. There are 2 instances of final EJB API 4.0.0 in staging:
```
[INFO]  * Connected to Nexus at https://jakarta.oss.sonatype.org:443/, is version 2.14.19-01 and edition "Professional"
[INFO] Getting list of available staging repositories...
[INFO] 
[INFO] ID                   State    Description                   
[INFO] jakartaejb-1002      CLOSED   jakarta.ejb:jakarta.ejb-api:4.0.0
[INFO] jakartaejb-1003      CLOSED   jakarta.ejb:jakarta.ejb-api:4.0.0
[INFO] ------------------------------------------------------------------------
```
the content of ``jakartaejb-1002`` is ``https://jakarta.oss.sonatype.org/content/repositories/jakartaejb-1002/jakarta/ejb/jakarta.ejb-api/4.0.0/`` and content of ``jakartaejb-1003`` is ``https://jakarta.oss.sonatype.org/content/repositories/jakartaejb-1003/jakarta/ejb/jakarta.ejb-api/4.0.0/``

due to staging specifics actual visible content at ``https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/ejb/jakarta.ejb-api/4.0.0/`` refers to ``jakartaejb-1002``
However I presume desired final version of EJB API 4.0.0 is published at ``jakartaejb-1003``.
So, before promoting to central one of stagings shall be removed (presumably ``jakartaejb-1002``)

Please kindly consider solving this before EJB API 4.0.0 is promoted to central.

**Comment by jeanouii** [comment]
The one to publish is the one we voted on in this PR

https://github.com/jakartaee/specifications/pull/258

So it's jakartaejb-1003

**Comment by senivam** [comment]
could you please drop jakartaejb-1002 then? Thank you

**Comment by jeanouii** [comment]
I don't know if I can do that. I might need to create a bugzilla ticket

**Comment by jeanouii** [comment]
Should be fixed and removed now. And the other has been successfully promoted.
https://repo.maven.apache.org/maven2/jakarta/ejb/jakarta.ejb-api/4.0.0/
