### ISSUE TITLE
Prepare Jakarta Enterprise Beans for Jakarta EE 9 Release

### ISSUE THREAD

**Issue by ederks85** [eclipse-ee4j/ejb-api#58]
I would like to assist with the work that needs to be done for Jakarta EE 9:

- [ ] javax > jakarta namespace in documentation
- [ ] javax > jakarta namespace in Java code
- [ ] ...

**Comment by m-reza-rahman** [comment]
I will help connect you to Oracle. They should help guide you in this work.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by smillidge** [comment]
Note there is a PR for the first step of the namespace change
https://github.com/eclipse-ee4j/ejb-api/pull/59

**Comment by ederks85** [comment]
Thanks @smillidge I see it now. Please let me know if there is anything futher I can do. I won't mind doing some grunt work to get accustomed with committing on specifications :)

**Comment by kwsutter** [comment]
@ederks85 The additional work is getting outlined in this other Issue #.  Maybe this Issue should be closed out?  Unless it's being used for more distinct work efforts? Thanks.

**Comment by ederks85** [comment]
@kwsutter I agree, this particular issue has been superseded by #62 so I will close it
