### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/ejb-api#8]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Working build jobs:
- master: https://jenkins.eclipse.org/ejb/job/ejb-api-master-build/
- EE4J_8: https://jenkins.eclipse.org/ejb/job/ejb-api-ee4j8-build/

@dblevins please delete
https://jenkins.eclipse.org/ejb/job/ejb-api-release-build/
https://jenkins.eclipse.org/ejb/job/ejb-api-release-job/

and close this task as done.
