### ISSUE TITLE
Prepare for next release 4.0.0-RC2

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/ejb-api#82]
- [api] Merge 4.0.0-RC1 branch in master
- [api] Add an empty relativePath to parent to resolve ee4j-parent from repository instead of parent directory
- [api] Legal documents in release jar are incorrect
 The CDDL license.txt is included in META-INF. This is pulled from org.glassfish:legal:1.1 by maven-remote-resources-plugin. This needs to be removed.
 The legal.doc.source property is pointing to current directory, this should be changed to parent directory. The License.md and Notice.md reside in the parent directory.
- [api] Remove the maven-release-plugin, maven-gpg-plugin and nexus-staging-maven-plugin as they are already configured in the parent
- [api] Upgrade java compiler source and target version from 1.6 to 1.8
- [api] Unable to build with JDK11 - Fix javadoc issues and configure maven-javadoc-plugin with source as 1.8
- [api] Prepare for 4.0.0-RC2
- [spec] asciidoc-to-html does not stamp project version, date and status in HTML output.
- [spec] Remove the maven-release-plugin as it is unused.

**Comment by tkburroughs** [comment]
@hussainnm Looks good; merged.  Thanks for getting these fixed; api jar looks good with correct classes, correct license files... and built just fine for me with Java 11.
